title: Column Sandbox
name: column-sandbox
name_short: col-sbox
program: tax-benefits
repo: codeforamerica/column-sandbox
internal: true
subdomain: tax
enabled: false
secrets:
  CLIENT_ID:
    description: Client ID and for Column Sandbox
    type: string
  CLIENT_SECRET:
    description: Client secret for Column Sandbox
    type: string
services:
  web:
    health_check_path: /
    expose: 3000
    public: true
    subdomain: column
    ports:
      - 3000
    volumes:
      data:
        type: persistent
        mount: /app/data
    secrets:
      CLIENT_ID:
        name: CLIENT_ID
      CLIENT_SECRET:
        name: CLIENT_SECRET
