name: Deploy documentation

on:
  workflow_dispatch:
    inputs:
      # Update the default environment if "development" is not suitable.
      environment:
        description: Environment to deploy to.
        default: development
        required: true
        type: environment
  push:
    paths:
      # Only trigger on changes to documentation files.
      - 'docs/**'
      - 'mkdocs.yaml'
      - '.github/workflows/docs.yaml'
      - '*.md'
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    # Update the default environment if "development" is not suitable.
    name: Deploy Documentation to ${{ inputs.environment || 'development'}}
    environment: ${{ inputs.environment || 'development'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION || 'us-east-1' }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      # Add any additional python dependencies here.
      - name: Install python dependencies
        run: |
          pip install \
            mkdocs-material \
            markdown-callouts \
            mdx_truly_sane_lists \
            mkdocs-nav-weight \
            pymdown-extensions
      # Update to add additional build steps if needed.
      - name: Build documentation
        run: mkdocs build
      # Make sure the prefix here matches your application's name from the app spec.
      - name: Sync documentation to S3
        run: aws s3 sync ./site "s3://${{ env.DOCS_BUCKET || 'docs.dev.services.cfa.codes' }}/${{ env.PREFIX || 'my-app' }}"
