name: Plan infrastructure changes

on:
  workflow_call:
    inputs:
      config:
        description: Configuration to deploy.
        required: true
        type: string
      environment:
        description: Environment to plan on.
        default: development
        required: true
        type: string
    outputs:
      plan:
        description: The plan output from the tofu plan command.
        value: ${{ jobs.plan.outputs.plan }}
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DOPPLER_TOKEN:
        required: true
      TF_VAR_PRIVATE_SUBNET_CIDRS:
        required: true
      TF_VAR_PUBLIC_SUBNET_CIDRS:
        required: true
      TF_VAR_VPC_CIDR:
        required: true
  workflow_dispatch:
    inputs:
      config:
        description: Configuration to deploy.
        required: true
        type: choice
        options:
          - foundation
          - networking
          - docs
      environment:
        description: Environment to plan on.
        default: development
        required: true
        type: environment

permissions:
  contents: read

jobs:
  plan:
    name: Plan on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      # Set required secrets and variables.
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      TF_VAR_private_subnet_cidrs: ${{ secrets.TF_VAR_PRIVATE_SUBNET_CIDRS }}
      TF_VAR_public_subnet_cidrs: ${{ secrets.TF_VAR_PUBLIC_SUBNET_CIDRS }}
      TF_VAR_vpc_cidr: ${{ secrets.TF_VAR_VPC_CIDR }}

      TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
      TF_VAR_program: ${{ vars.TF_VAR_PROGRAM }}
      TF_VAR_project: ${{ vars.TF_VAR_PROJECT }}

      # Set an application variable so that if we end up planning the hosting
      # config, it has a value.
      TF_VAR_application: ${{ vars.TF_VAR_DEFAULT_APPLICATION }}
    outputs:
      plan: ${{ steps.plan.outputs.stdout }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
      - name: Setup OpenTofu
        uses: ./.github/actions/setup-opentofu
        with:
          config: ${{ inputs.config }}
      - name: Plan changes
        working-directory: ./tofu/config/${{ inputs.config }}
        run: tofu plan -concise -no-color -out tfplan > plan.txt
      - name: Display plan
        working-directory: ./tofu/config/${{ inputs.config }}
        run: tofu show -plan tfplan
      - name: Upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.config }}-tfplan
          path: |
            ./tofu/config/${{ inputs.config }}/plan.txt
            ./tofu/config/${{ inputs.config }}/tfplan
          retention-days: 5
